"""
Anthropic Claude NLP provider for cloud-based inference.
"""

from typing import Dict, Any
from .base import NLPProvider, NLPContext, NLPResult

try:
    from anthropic import AsyncAnthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False


class AnthropicProvider(NLPProvider):
    """Provider that uses Anthropic Claude API for command translation."""

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)

        if not ANTHROPIC_AVAILABLE:
            raise ImportError(
                "Anthropic library not installed. "
                "Install with: pip install anthropic"
            )

        api_key = config.get('api_key')
        if not api_key:
            raise ValueError("Anthropic API key is required")

        self.client = AsyncAnthropic(api_key=api_key)
        self.model = config.get('model', 'claude-3-5-sonnet-20241022')
        self.max_tokens = config.get('max_tokens', 150)
        self.temperature = config.get('temperature', 0.1)

    def _build_system_prompt(self, context: NLPContext) -> str:
        """Build system prompt with context."""
        prompt = """You are a shell command expert. Your job is to translate natural language requests into shell commands.

CRITICAL RULES:
1. Output ONLY the shell command - no explanations, no markdown, no code blocks
2. Do not include $ or # prefixes
3. Do not add any commentary before or after the command
4. Just the command itself, nothing else

Guidelines:
- Use common flags and best practices
- For destructive operations, include safety flags (e.g., -i for interactive)
- Use modern alternatives when appropriate (e.g., ripgrep over grep)
- If multiple commands are needed, chain with && or ;
- Prefer portable commands that work across Unix-like systems

Context:
"""
        prompt += f"- Current directory: {context.cwd}\n"
        prompt += f"- Operating System: {context.os_type}\n"
        prompt += f"- Shell: {context.shell_type}\n"

        if context.project_type:
            prompt += f"- Project type: {context.project_type}\n"

        return prompt

    def _build_user_prompt(self, user_input: str, context: NLPContext) -> str:
        """Build user prompt."""
        prompt = f"Translate this to a shell command: {user_input}"

        if context.recent_commands:
            recent = context.recent_commands[-3:]
            prompt += f"\n\nRecent commands for context:\n" + "\n".join(f"- {cmd}" for cmd in recent)

        return prompt

    async def translate(
        self,
        user_input: str,
        context: NLPContext
    ) -> NLPResult:
        """Translate using Anthropic Claude API."""
        try:
            response = await self.client.messages.create(
                model=self.model,
                max_tokens=self.max_tokens,
                temperature=self.temperature,
                system=self._build_system_prompt(context),
                messages=[
                    {
                        "role": "user",
                        "content": self._build_user_prompt(user_input, context)
                    }
                ]
            )

            # Extract command from response
            command = response.content[0].text.strip()

            # Clean up response
            command = self._clean_command(command)

            # Claude provides stop_reason, use it for confidence
            confidence = 0.95 if response.stop_reason == 'end_turn' else 0.8

            return NLPResult(
                command=command,
                confidence=confidence,
                source='anthropic',
                explanation=f"Generated by {self.model}"
            )

        except Exception as e:
            raise Exception(f"Anthropic translation failed: {str(e)}")

    def _clean_command(self, command: str) -> str:
        """Clean up the generated command."""
        # Remove markdown code blocks
        if command.startswith('```'):
            lines = command.split('\n')
            if len(lines) > 2:
                command = '\n'.join(lines[1:-1])
            command = command.replace('```bash', '').replace('```sh', '').replace('```', '')

        # Remove common prefixes
        prefixes = ['$ ', '> ', '# ', 'Command: ', 'command: ', 'Shell command: ']
        for prefix in prefixes:
            if command.startswith(prefix):
                command = command[len(prefix):]

        # If multiple lines without chaining, take first line
        if '\n' in command and not any(op in command for op in ['&&', '||', '|', ';']):
            command = command.split('\n')[0]

        return command.strip()

    async def test_connection(self) -> bool:
        """Test connection to Anthropic API."""
        try:
            # Simple test request
            response = await self.client.messages.create(
                model=self.model,
                max_tokens=10,
                messages=[{"role": "user", "content": "test"}]
            )
            return len(response.content) > 0
        except Exception:
            return False

    @staticmethod
    def get_available_models() -> Dict[str, Dict[str, Any]]:
        """Get list of available Anthropic models."""
        return {
            'claude-3-5-sonnet-20241022': {
                'name': 'Claude 3.5 Sonnet',
                'description': 'Most capable and intelligent',
                'cost_per_1k_tokens': 0.003,
                'recommended': True,
            },
            'claude-3-5-haiku-20241022': {
                'name': 'Claude 3.5 Haiku',
                'description': 'Fast and cost-effective',
                'cost_per_1k_tokens': 0.0008,
                'recommended': True,
            },
            'claude-3-opus-20240229': {
                'name': 'Claude 3 Opus',
                'description': 'Previous generation, very capable',
                'cost_per_1k_tokens': 0.015,
                'recommended': False,
            },
        }
