"""
Google Gemini NLP provider for cloud-based inference.
Supports both free and paid tiers.
"""

from typing import Dict, Any
from .base import NLPProvider, NLPContext, NLPResult

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


class GeminiProvider(NLPProvider):
    """Provider that uses Google Gemini API for command translation."""

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)

        if not GEMINI_AVAILABLE:
            raise ImportError(
                "Google Generative AI library not installed. "
                "Install with: pip install google-generativeai"
            )

        api_key = config.get('api_key')
        if not api_key:
            raise ValueError("Gemini API key is required")

        genai.configure(api_key=api_key)

        # Model selection (free tier uses gemini-pro, paid can use gemini-1.5-pro)
        self.model_name = config.get('model', 'gemini-pro')
        self.tier = config.get('tier', 'free')  # 'free' or 'paid'
        self.max_tokens = config.get('max_tokens', 150)
        self.temperature = config.get('temperature', 0.1)

        # Initialize model
        self.model = genai.GenerativeModel(self.model_name)

    def _build_prompt(self, user_input: str, context: NLPContext) -> str:
        """Build prompt for Gemini."""
        prompt = """You are a shell command expert. Translate natural language requests into shell commands.

IMPORTANT: Output ONLY the shell command with no explanations, no markdown, no code blocks, no prefixes.

Context:
"""
        prompt += f"- Current directory: {context.cwd}\n"
        prompt += f"- Operating System: {context.os_type}\n"
        prompt += f"- Shell: {context.shell_type}\n"

        if context.project_type:
            prompt += f"- Project type: {context.project_type}\n"

        if context.recent_commands:
            recent = context.recent_commands[-3:]
            prompt += f"- Recent commands: {', '.join(recent)}\n"

        prompt += f"""
Rules:
1. Output ONLY the command, nothing else
2. Use common flags and best practices
3. For destructive operations, include safety flags
4. Use modern alternatives when appropriate
5. If multiple commands needed, use && or ; to chain them

Translate this request to a shell command:
{user_input}

Command:"""

        return prompt

    async def translate(
        self,
        user_input: str,
        context: NLPContext
    ) -> NLPResult:
        """Translate using Gemini API."""
        try:
            prompt = self._build_prompt(user_input, context)

            # Configure generation
            generation_config = genai.types.GenerationConfig(
                temperature=self.temperature,
                max_output_tokens=self.max_tokens,
            )

            # Generate response
            response = await self.model.generate_content_async(
                prompt,
                generation_config=generation_config
            )

            command = response.text.strip()

            # Clean up response
            command = self._clean_command(command)

            # Gemini doesn't provide confidence scores, use a reasonable default
            confidence = 0.9

            return NLPResult(
                command=command,
                confidence=confidence,
                source='gemini',
                explanation=f"Generated by {self.model_name} ({self.tier} tier)"
            )

        except Exception as e:
            raise Exception(f"Gemini translation failed: {str(e)}")

    def _clean_command(self, command: str) -> str:
        """Clean up the generated command."""
        # Remove markdown code blocks
        if command.startswith('```'):
            lines = command.split('\n')
            if len(lines) > 2:
                command = '\n'.join(lines[1:-1])
            command = command.replace('```bash', '').replace('```sh', '').replace('```', '')

        # Remove common prefixes
        prefixes = ['$ ', '> ', '# ', 'Command: ', 'command: ', 'Shell command: ']
        for prefix in prefixes:
            if command.lower().startswith(prefix.lower()):
                command = command[len(prefix):]

        # If multiple lines without chaining operators, take first line
        if '\n' in command and not any(op in command for op in ['&&', '||', '|', ';']):
            command = command.split('\n')[0]

        return command.strip()

    async def test_connection(self) -> bool:
        """Test connection to Gemini API."""
        try:
            # Simple test request
            response = await self.model.generate_content_async("test")
            return response.text is not None
        except Exception:
            return False

    @staticmethod
    def get_available_models() -> Dict[str, Dict[str, Any]]:
        """Get list of available Gemini models."""
        return {
            'gemini-pro': {
                'name': 'Gemini Pro',
                'description': 'Free tier model, fast and capable',
                'tier': 'free',
                'rate_limit': '60 requests/minute',
                'recommended': True,
            },
            'gemini-1.5-pro': {
                'name': 'Gemini 1.5 Pro',
                'description': 'Advanced model with larger context',
                'tier': 'paid',
                'rate_limit': 'Higher limits',
                'recommended': True,
            },
            'gemini-1.5-flash': {
                'name': 'Gemini 1.5 Flash',
                'description': 'Fast and efficient for simple tasks',
                'tier': 'free',
                'rate_limit': '1000 requests/minute',
                'recommended': False,
            },
        }
