"""
OpenAI NLP provider for cloud-based inference.
"""

from typing import Dict, Any, Optional
from .base import NLPProvider, NLPContext, NLPResult

try:
    from openai import AsyncOpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


class OpenAIProvider(NLPProvider):
    """Provider that uses OpenAI API for command translation."""

    def __init__(self, config: Dict[str, Any]):
        super().__init__(config)

        if not OPENAI_AVAILABLE:
            raise ImportError(
                "OpenAI library not installed. "
                "Install with: pip install openai>=1.0.0"
            )

        api_key = config.get('api_key')
        if not api_key:
            raise ValueError("OpenAI API key is required")

        self.client = AsyncOpenAI(api_key=api_key)
        self.model = config.get('model', 'gpt-3.5-turbo')
        self.max_tokens = config.get('max_tokens', 150)
        self.temperature = config.get('temperature', 0.1)

    def _build_system_prompt(self, context: NLPContext) -> str:
        """Build system prompt with context."""
        prompt = """You are a shell command expert. Your job is to translate natural language requests into shell commands.

Rules:
1. Output ONLY the shell command, no explanations, no markdown, no code blocks
2. Use common flags and best practices
3. For destructive operations, include safety flags (e.g., -i for interactive confirmation)
4. Use modern alternatives when appropriate (e.g., exa over ls, ripgrep over grep)
5. If multiple commands are needed, separate them with && or ;
6. Prefer portable commands that work across different Unix-like systems

Context:
"""
        prompt += f"- Current directory: {context.cwd}\n"
        prompt += f"- Operating System: {context.os_type}\n"
        prompt += f"- Shell: {context.shell_type}\n"

        if context.project_type:
            prompt += f"- Project type: {context.project_type}\n"

        return prompt

    def _build_user_prompt(self, user_input: str, context: NLPContext) -> str:
        """Build user prompt with recent context."""
        prompt = f"Translate this to a shell command: {user_input}"

        if context.recent_commands:
            recent = context.recent_commands[-3:]
            prompt += f"\n\nRecent commands for context:\n" + "\n".join(f"- {cmd}" for cmd in recent)

        return prompt

    async def translate(
        self,
        user_input: str,
        context: NLPContext
    ) -> NLPResult:
        """Translate using OpenAI API."""
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": self._build_system_prompt(context)
                    },
                    {
                        "role": "user",
                        "content": self._build_user_prompt(user_input, context)
                    }
                ],
                temperature=self.temperature,
                max_tokens=self.max_tokens,
            )

            command = response.choices[0].message.content.strip()

            # Clean up response
            command = self._clean_command(command)

            # Get confidence from finish_reason
            confidence = 0.95 if response.choices[0].finish_reason == 'stop' else 0.7

            return NLPResult(
                command=command,
                confidence=confidence,
                source='openai',
                explanation=f"Generated by {self.model}"
            )

        except Exception as e:
            raise Exception(f"OpenAI translation failed: {str(e)}")

    def _clean_command(self, command: str) -> str:
        """Clean up the generated command."""
        # Remove markdown code blocks
        if command.startswith('```'):
            lines = command.split('\n')
            if len(lines) > 2:
                command = '\n'.join(lines[1:-1])
            command = command.replace('```bash', '').replace('```sh', '').replace('```', '')

        # Remove common prefixes
        prefixes = ['$ ', '> ', '# ', 'Command: ', 'command: ']
        for prefix in prefixes:
            if command.startswith(prefix):
                command = command[len(prefix):]

        # If multiple lines, take only the first (main command)
        if '\n' in command and not any(cmd in command for cmd in ['&&', '||', '|', ';']):
            command = command.split('\n')[0]

        return command.strip()

    async def test_connection(self) -> bool:
        """Test connection to OpenAI API."""
        try:
            # Simple test request
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": "test"}],
                max_tokens=5
            )
            return response.choices[0].message.content is not None
        except Exception:
            return False

    @staticmethod
    def get_available_models() -> Dict[str, Dict[str, Any]]:
        """Get list of recommended OpenAI models."""
        return {
            'gpt-3.5-turbo': {
                'name': 'GPT-3.5 Turbo',
                'description': 'Fast and cost-effective',
                'cost_per_1k_tokens': 0.0015,
                'recommended': True,
            },
            'gpt-4': {
                'name': 'GPT-4',
                'description': 'Most capable, higher cost',
                'cost_per_1k_tokens': 0.03,
                'recommended': False,
            },
            'gpt-4-turbo-preview': {
                'name': 'GPT-4 Turbo',
                'description': 'Fast GPT-4 with lower cost',
                'cost_per_1k_tokens': 0.01,
                'recommended': True,
            },
        }
